version: "2"

services:
  drupal:
    image: drupal:8.8.2
    ports: 
      - "8081:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
  postgres:
    image: postgres:12.1
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass

volumes:
  drupal_modules:
  drupal_profiles
  drupal_themes
  drupal_sites
